### PR TITLE
Updated translations

### PR DESCRIPTION
**Pull request by mayumih387**
Hi, thanks as always for the grate app.

# PR Details

I have checked new Japanese translations added to the latest version, and revised them to make them sound more natural.

The only thing I couldn't find was the translation for notifications; there are still some unnatural translations.

## Description

Revised some phrases by human.

## Related Issue

issue/598

## Motivation and Context

Some phrases didn't seem very natural so I changed them.

## How Has This Been Tested

On local

## Types of changes

- [ x] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by estruyf** [comment]
@mayumih387 oh, thank you! 🙏

Currently, translations are generated during each build for the keys not present in the localization file. That is probably why you don't find those in the [l10n](https://github.com/estruyf/vscode-front-matter/tree/main/l10n) files. It is best to search for the string/key in the EN file and copy its key to the l10n of the language (Japanese in your case) you want to change.

**Comment by mayumih387** [comment]
Thanks, I see now the `bundle.l10n.ja.json` is missing keys compared to `bundle.l10n.json` on the main branch. Is it okay if I add the keys from the main branch to this branch and send a new PR here?

**Comment by estruyf** [comment]
Yes, that ensures the key/value pairs are translated by a human. When missing, it is using machine translation by Azure Translation Services.

**Comment by estruyf** [comment]
Oh, @mayumih387, I just noticed you used the `localization` branch. Would you be able to use the `dev` branch?

I'll remove the localization branch, as this was only there for the initial localization steps.

**Comment by mayumih387** [comment]
Noted!

**Pull request closed without merging**
