### PR TITLE
Added Japanese Translation

### PR DESCRIPTION
**Pull request by mayumih387**
# PR Details

Translation into Japanese:
-  package.nls.ja.json
-  l10n/bundle.l10n.ja.json

## Description

New contexts are added and translated from the original `package.nls.json` and `l10n/bundle.l10n.json` based on [78bfa62](https://github.com/estruyf/vscode-front-matter/commit/78bfa62ed4af8cdfa447e3307c973cf678ad544a).
Most of them have been translated, except for 2 following lines;

l10n/bundle.l10n.json
- 468 "commands.article.notification.noTaxonomy"
- 641 "helpers.questions.selectContentFolder.quickPick.noFolders.warning"

This is because I couldn't be sure in which situation these phrases would appear. I have added 🚧 to these lines. If necessary, please delete the marker, or if the practical information for these phrases is available, I can add translations.

## Related Issue

none

## Motivation and Context

For Japanese users

## How Has This Been Tested

- on local
- vsce

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by estruyf** [comment]
@mayumih387 amazing work! Will verify the two lines and let you know what to do. Thank you!

**Comment by estruyf** [comment]
The first one can be ignored, this is coming from old functionality. Will remove the reference.

**Comment by estruyf** [comment]
The second one is obsolete as well, because, when there are no page folders configured, the welcome view will be shown to highlight configuration is missing.

Just did the changes and will merge your PR.

**Comment by mayumih387** [comment]
Thanks for checking! Please let me know if any further translation is needed :)

**Comment by estruyf** [comment]
@mayumih387 just pushed a commit for #731, which includes a couple of new keys that might need translation.

**Comment by mayumih387** [comment]
I'd love to. I'm sending a new PR.

**Pull request merged**
