### PR TITLE
#705 - UI tweaks and accessibility changes

### PR DESCRIPTION
**Pull request by T3sT3ro**
# PR Details

- UI tweaks to the new keywords insights section

Now it looks like this:

image

## Description

- adjusted styles  and colors
- allow keywords to span multiple lines
- added tooltip for frequency and why it's colored
- enlarged icons to preserve details
- made badges more pleasant to look at
- improved contrast of the warning badges
- changed tag delete styling to color whole tag red, given nice transition
- simplified some related code

#705
## Motivation and Context

see #705

## How Has This Been Tested

Locally, manually, viewed on different VSCode themes.

## Types of changes

- [x] ~~Docs change~~ / refactoring / ~~dependency upgrade~~
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by T3sT3ro** [comment]
I don't know why, but ever since the first time I booted it, I had this problem when trying to hover over the checks tooltip:

image

**Review by estruyf — APPROVED** [review]

**Comment by estruyf** [comment]
Thanks @T3sT3ro for your contribution 🤩🙏

**Comment by T3sT3ro** [comment]
Some images also should be updated in the docs with it. For example ones on the [the panel page ](https://frontmatter.codes/docs/panel). I don't know if there are other places. I don't know what theme you use in your editor and it's different than mine. I am currently swamped so I don't have the time to update those screenshots, could you in your spare time?

**Comment by estruyf** [comment]
For the documentation, I started to use the Front Matter CMS theme - https://marketplace.visualstudio.com/items?itemName=eliostruyf.vscode-frontmatter-theme

I added it on my task list.

**Pull request merged**
