### PR TITLE
Added Japanese translation

### PR DESCRIPTION
**Pull request by mayumih387**
# Added Japanese translation

## Description

Added a new Japanese translation file

## Related Issue

None

## Motivation and Context

We still have to add other keys.

## How Has This Been Tested

On local

## Types of changes

- [ ] Docs change / refactoring / dependency upgrade
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### CODE REVIEW

**Comment by estruyf** [comment]
@mayumih387, all the EN translations for the webviews are in. Would you be able to update this PR? Fields you already worked on got changed a bit, so it best is to start over.

Next up are the commands and settings.

**Comment by mayumih387** [comment]
Thanks for your work @estruyf, I have started to work on it.

Something I just noticed; line 184 seems unclear.

```
"dashboard.media.media.currentFolder": "Content folder",
```

"current", or "content"? "current" looks correct, though :)

**Comment by estruyf** [comment]
The value is correct. The key needs to be updated to: `dashboard.media.media.contentFolder`. I will push out an update.

**Comment by estruyf** [comment]
The commands and settings have been put in a localization file `package.nls.json` (in the root of the project). If you want, they can be localized by creating a new `package.nls.<locale>.json` file and copy the contents of the EN version.

**Comment by estruyf** [comment]
The commands and settings have been put in a localization file `package.nls.json` (in the root of the project). If you want, they can be localized by creating a new `package.nls.<locale>.json` file and copy the contents of the EN version.

**Comment by estruyf** [comment]
The commands and settings have been put in a localization file `package.nls.json` (in the root of the project). If you want, they can be localized by creating a new `package.nls.<locale>.json` file and copy the contents of the EN version.

**Comment by mayumih387** [comment]
I have added translations. (I'm not sure if I should send PR again or new files are already reflected to be reviewed)

### package.nls.ja.json

I have added translations only for the lines currently shown in settings.

I also checked and reviced documentation URLs in package.nls.json, and found some of URLs didn't exist:

```
82 https://frontmatter.codes/docs/settings/overview#frontMatter.snippets.wrapper.enabled
83 https://frontmatter.codes/docs/settings/overview#frontmatter.content.snippets
107 https://frontmatter.codes/docs/settings/overview#frontmatter.dashboard.content.card.fields.state
108 https://frontmatter.codes/docs/settings/overview#frontMatter.dashboard.content.card.fields.date
109 https://frontmatter.codes/docs/settings/overview#frontMatter.dashboard.content.card.fields.description
110 https://frontmatter.codes/docs/settings/overview#frontMatter.dashboard.content.card.fields.title
```

I just leave them as they are.

### bundle.l10n.ja.json

Fully updated, left only line 381 `"panel.seoDetails.recommended"` not tranlated yet because it seems not to be used anywhere for now. I'll add its translation once I'd find how the word is treated.

Thanks!

**Comment by estruyf** [comment]
Thank you so much @mayumih387 🙏

**package.nls.ja.json**

About the settings, that is correct, those are part of the new upcoming release. That is why they do not yet exist in the docs.

**bundle.l10n.ja.json**

I'll check if we can remove this.

**Pull request merged**
